"""
Django settings for mousetube_api project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

import environ
from django.core.management.utils import get_random_secret_key

# Add two custom countries to django_countries
COUNTRIES_OVERRIDE = {
    "EU": {"names": ["European Union"], "alpha3": "EUN", "numeric": 998},
    "GO": {"names": ["Global"], "alpha3": "GLO", "numeric": 999},
}

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/


env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False),
)

env_files = [
    BASE_DIR / ".env",
    Path("/etc/mousetube/mousetube.env"),
]

for env_path in env_files:
    if env_path.exists():
        env.read_env(str(env_path))
        break

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG", default=True)
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = (
    env("SECRET_KEY") if env("SECRET_KEY", default=None) else get_random_secret_key()
)

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["localhost,127.0.0.1"])
# CORS_ORIGIN_ALLOW_ALL = True

CORS_ALLOWED_ORIGINS = env.list(
    "CORS_ALLOWED_ORIGINS",
    default=[
        "http://localhost:3000",
        "http://127.0.0.1:3000",
        "https://mousetube.local",
    ],
)

CSRF_TRUSTED_ORIGINS = env.list(
    "CSRF_TRUSTED_ORIGINS",
    default=[
        "http://localhost:3000",
        "http://127.0.0.1:3000",
        "https://mousetube.local",
    ],
)
CORS_ALLOW_CREDENTIALS = True
X_FRAME_OPTIONS = "ALLOW-FROM http://127.0.0.1:8001"

SECURE_SSL_REDIRECT = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG

USE_X_FORWARDED_HOST = env.bool("USE_X_FORWARDED_HOST", default=False)
SECURE_PROXY_SSL_HEADER = env.tuple(
    "SECURE_PROXY_SSL_HEADER", default=("HTTP_X_FORWARDED_PROTO", "https")
)

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "mousetube_api",
    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",
    "djoser",
    "django.contrib.sites",
    "django_celery_results",
    "celery_progress",
    "drf_spectacular",
    "django_extensions",
    "django_countries",
    "django_filters",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.orcid",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "mousetube_api.middleware.OrcidProcessSessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "mousetube_api.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "mousetube_api/templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

ADMIN_BASE_TEMPLATE = "admin/base_site.html"
WSGI_APPLICATION = "mousetube_api.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Database
IS_DOCKER = env.bool("DJANGO_RUNNING_IN_DOCKER", default=False)
DATABASES = {
    "default": {
        "ENGINE": env("DB_ENGINE", default="django.db.backends.mysql"),
        "NAME": env("DB_NAME", default=""),
        "USER": env("DB_USER", default=""),
        "PASSWORD": env("DB_PASSWORD", default=""),
        "HOST": env("DB_HOST", default="127.0.0.1"),
        "PORT": "3306" if IS_DOCKER else env("DB_PORT", default="3306"),
        "OPTIONS": {}
        if not env.bool("DB_SSL", default=False)
        else {
            "ssl": {
                "ca": env("DB_SSL_CA", default=None),
                "cert": env("DB_SSL_CERT", default=None),
                "key": env("DB_SSL_KEY", default=None),
            }
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media/")

AUDIO_IMG_DIR = os.path.join(MEDIA_ROOT, "audio_images")


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

APPEND_SLASH = True

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        # "rest_framework.authentication.TokenAuthentication",
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        # 'rest_framework.permissions.IsAuthenticated',
        # 'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly',
        "rest_framework.permissions.AllowAny",
    ],
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Mousetube API",
    "DESCRIPTION": "API Documentation",
    "VERSION": "1.0.0",
    "PREPROCESSING_HOOKS": [
        "mousetube_api.utils.swagger_hooks.remove_auth_paths",
    ],
    "SERVE_INCLUDE_SCHEMA": False,
}

SITE_ID = 1

SOCIALACCOUNT_PROVIDERS = {
    "orcid": {
        "APP": {
            "client_id": env("CLIENT_ID", default=""),
            "secret": env("CLIENT_SECRET", default=""),
        },
        "LOGIN_URL": "/accounts/orcid/login/",
        "SCOPE": ["/authenticate"],
        "AUTH_PARAMS": {"access_type": "online"},
    }
}

SOCIALACCOUNT_ADAPTER = "mousetube_api.utils.adapters.MySocialAccountAdapter"

# Django Allauth settings
ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = [
    "email*",
    "password1*",
    "password2*",
    "first_name",
    "last_name",
]
ACCOUNT_EMAIL_VERIFICATION = "none"
SOCIALACCOUNT_AUTO_SIGNUP = False
ACCOUNT_SESSION_REMEMBER = None
ACCOUNT_LOGOUT_ON_GET = False
SOCIALACCOUNT_EMAIL_VERIFICATION = "none"
ACCOUNT_CONFIRM_EMAIL_ON_GET = False
SESSION_COOKIE_SECURE = True
SESSION_COOKIE_SAMESITE = "None"
CSRF_COOKIE_SECURE = True
CSRF_COOKIE_SAMESITE = "None"

# Djoser settings
DJOSER = {
    "SEND_ACTIVATION_EMAIL": True,
    "ACTIVATION_URL": "activate/{uid}/{token}",
    "SERIALIZERS": {
        "user_create": "mousetube_api.serializers.CustomUserCreateSerializer",
    },
    "USER_CREATE_FIELDS": [
        "username",
        "email",
        "password",
        "first_name",
        "last_name",
        "orcid",
    ],
    "EMAIL": {
        "activation": "mousetube_api.utils.email_activation.CustomActivationEmail",
        "password_reset": "mousetube_api.utils.email_reset.CustomPasswordResetEmail",
    },
    "PASSWORD_RESET_CONFIRM_URL": "password/reset/confirm/{uid}/{token}",
    "DOMAIN": env("FRONT_DOMAIN", default="localhost:3000"),
    "SITE_NAME": "mouseTube",
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=12),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
}

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
DEFAULT_FROM_EMAIL = "no-reply@mousetube.com"

# use broker_url "redis://127.0.0.1:6379/0" on local dev
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://redis:6379/0")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "Europe/Paris"
# CELERY_IMPORTS = "mousetube_api.tasks"
CELERY_IMPORTS = ["mousetube_api.tasks"]
CELERY_RESULT_BACKEND = "django-db"
CACHE_BACKEND = "memcached://127.0.0.1:11211/"

ZENODO_TOKEN = env("ZENODO_TOKEN", default="")

LOGS_DIR = Path(BASE_DIR) / "logs"
LOGS_DIR.mkdir(exist_ok=True)

FRONT_DOMAIN = env("FRONT_DOMAIN", default="localhost:3000")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{asctime}] {levelname} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "dead_links_info_file": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": os.path.join(BASE_DIR, "logs", "dead_links_info.log"),
            "formatter": "verbose",
        },
        "dead_links_error_file": {
            "level": "WARNING",
            "class": "logging.FileHandler",
            "filename": os.path.join(BASE_DIR, "logs", "dead_links_error.log"),
            "formatter": "verbose",
        },
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "check_dead_links": {
            "handlers": ["dead_links_info_file", "dead_links_error_file"],
            "level": "INFO",
            "propagate": False,
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}
